---
- name: Install Ghost and the required dependencies
  hosts: localhost
  remote_user: trace
  become: yes
  become_method: sudo

  roles:
    - common
    - nginx
    - mysql
    - mise
    - node
    - ghost
