---
- name: "Debian install"
  hosts: localhost
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core

  tasks:
    - include_tasks: debian_tasks/core-setup.yml # noqa: name[missing]
    - include_tasks: debian_tasks/node-setup.yml # noqa: name[missing]
    - include_tasks: debian_tasks/git-setup.yml # noqa: name[missing]
    - include_tasks: debian_tasks/npm-packages.yml # noqa: name[missing]
