---
- name: Perform apt update
  ansible.builtin.apt:
    update_cache: yes

- name: Upgrade the OS (apt-get dist-upgrade)
  ansible.builtin.apt:
    upgrade: yes

- name: Install build essentials
  ansible.builtin.apt:
    name: build-essential
