---
- name: Perform apt update
  ansible.builtin.apt:
    update_cache: yes
  tags:
    - common

- name: Upgrade the OS (apt-get dist-upgrade)
  ansible.builtin.apt:
    upgrade: yes
  tags:
    - common

- name: Install build essentials
  ansible.builtin.apt:
    name: build-essential
  tags:
    - common

- name: Install certificate dependencies
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
  tags:
    - common
